flink_operator_release_name: flink-kubernetes-operator
flink_operator_namespace: flink-operator
flink_operator_deployment_name: flink-kubernetes-operator

flink_operator_chart_version: "1.14.0"
flink_operator_repo_name: flink-operator
flink_operator_repo_url: "https://archive.apache.org/dist/flink/flink-kubernetes-operator-{{ flink_operator_chart_version }}/"
flink_operator_chart_ref: "{{ flink_operator_repo_name }}/flink-kubernetes-operator"

flink_operator_helm_timeout: 10m
flink_operator_rollout_timeout: 10m
flink_operator_crd_wait_timeout: 5m
flink_operator_wait_for_crds: true

flink_operator_replicas: 1
flink_operator_watch_namespaces: []
flink_operator_webhook_enabled: true
flink_operator_rbac_nodes_rule_enabled: false
