minio_release_name: minio
minio_namespace: minio

minio_repo_name: minio
minio_repo_url: https://charts.min.io/
minio_chart_ref: "{{ minio_repo_name }}/minio"
minio_chart_version: "5.4.0"

minio_helm_timeout: 15m
minio_rollout_timeout: 10m

minio_mode: distributed
minio_replicas: "{{ groups['workers'] | length }}"
minio_drives_per_node: 1
minio_pools: 1

minio_root_user: "minioadmin"
minio_root_password: "minioadmin"

minio_persistence_enabled: true
minio_persistence_storage_class: local-path
minio_persistence_size: 150Gi
minio_persistence_access_mode: ReadWriteOnce
minio_storage_class_auto_create: true
minio_storage_class_manifest_url: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.32/deploy/local-path-storage.yaml
minio_storage_class_name: local-path
minio_storage_class_provisioner_namespace: local-path-storage
minio_storage_class_provisioner_deployment: local-path-provisioner
minio_storage_class_wait_timeout: 5m
minio_force_reinstall_on_storage_class_mismatch: false

minio_node_selector: {}
minio_tolerations: []
minio_topology_spread_constraints: []
minio_affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - minio
      topologyKey: kubernetes.io/hostname

minio_service_type: ClusterIP
minio_service_port: 9000
minio_service_node_port: 32000
minio_service_load_balancer_ip: ""

minio_console_service_type: ClusterIP
minio_console_service_port: 9001
minio_console_service_node_port: 32001
minio_console_service_load_balancer_ip: ""

minio_ingress_enabled: false
minio_ingress_class_name: haproxy
minio_ingress_host: "minio.{{ domain }}"
minio_ingress_path: /
minio_ingress_annotations: {}
minio_ingress_tls_enabled: false
minio_ingress_tls_secret_name: minio-tls

minio_console_ingress_enabled: false
minio_console_ingress_class_name: haproxy
minio_console_ingress_host: "minio-console.{{ domain }}"
minio_console_ingress_path: /
minio_console_ingress_annotations: {}
minio_console_ingress_tls_enabled: false
minio_console_ingress_tls_secret_name: minio-console-tls

minio_resources_requests_cpu: 250m
minio_resources_requests_memory: 512Mi
minio_resources_limits_cpu: ""
minio_resources_limits_memory: ""
