- name: Ensure firewalld installed
  ansible.builtin.dnf:
    name: firewalld
    state: present
  when: firewalld_enabled | default(true)

- name: Ensure firewalld running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true
  when: firewalld_enabled | default(true)

- name: Add/Update firewalld ports
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    state: enabled
  loop: "{{ merged_ports }}"
  when: firewalld_enabled | default(true)

- name: Add/Update firewalld services
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ merged_services }}"
  when: firewalld_enabled | default(true)

- name: Add/Update firewalld rich rules
  ansible.posix.firewalld:
    zone: "{{ firewalld_zone | default('public') }}"
    rich_rule: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ merged_rich_rules }}"
  when: firewalld_enabled | default(true)

- name: Put Pod CIDR to trusted zone
  ansible.posix.firewalld:
    source: "{{ pod_cidr }}"
    zone: "{{ firewalld_cidr_zone }}"
    state: enabled
    permanent: true
  when: firewalld_enabled | default(true)

- name: Put Service CIDR to trusted zone
  ansible.posix.firewalld:
    source: "{{ service_cidr }}"
    zone: "{{ firewalld_cidr_zone }}"
    state: enabled
    permanent: true
  when: firewalld_enabled | default(true)

- name: Allow port fowarding
  ansible.builtin.command: |
    firewall-cmd --permanent --add-masquerade
  when: firewalld_enabled | default(true)

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false
  when: firewalld_enabled | default(true)

- name: Apply hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
