---
- name: Install Flink Kubernetes Operator
  hosts: all
  gather_facts: true
  become: true
  vars:
    first_cp: "{{ groups['control_plane'][0] }}"
  tasks:
  - include_role:
      name: install_flink_operator
