---
- name: Install kubeadm HA bootstrap with kube-vip
  hosts: all
  gather_facts: true
  become: true
  vars:
    first_cp: "{{ groups['control_plane'][0] }}"
  tasks:
  - include_role:
      name: install_kubeadm_ha
