---
- name: Shut down nodes to turn off the lab cluster
  hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: Shut down immediately
    ansible.builtin.shell: systemctl poweroff
    async: 60
    poll: 0
    ignore_unreachable: true
    changed_when: true
